ecomapp/urls.py
from django.urls import path
from .views import *

app_name = "ecomapp"
urlpatterns = [
    path("", HomeView.as_view(), name ="home"),
    path("all-products/", AllProductsView.as_view(), name ="allproducts"),
    path("products/<slug:slug>/", ProductDetailView.as_view(), name ="productdetail"),
    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name ="addtocart"),
    path("my-cart/", MyCartView.as_view(), name ="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name ="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name ="emptycart"),
    path("checkout/", CheckoutView.as_view(), name ="checkout"),
    path("register/", CustomerRegistrationView.as_view(), name ="customerregistration"),
    path("logout/", CustomerLogoutView.as_view(), name ="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name ="customerlogin"),
    path("profile/", CustomerProfileView.as_view(), name ="customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(), name ="customerorderdetail"),

    path("admin-login/", AdminLoginView.as_view(), name ="adminlogin"),
    path("admin-home/", AdminHomeView.as_view(), name ="adminhome"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(), name ="adminorderdetail"),
    path("admin-all-orders/", AdminOrderListView.as_view(), name ="adminorderlist"),
    path("admin-order-<int:pk>-change/", AdminOrderStatusChangeView.as_view(), name ="adminorderstatuschange"),

    path("search/", SearchView.as_view(), name ="search"),
    path("khalti/", KhaltiView.as_view(), name="khalti"),
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),
]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("ecomapp.urls")),
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

STATUS = (('active','Active'),('inactive','Inactive'))

class Ad(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='products')
    rank = models.IntegerField()
    status = models.CharField(choices=STATUS, max_length=100)
    def __str__(self):
        return self.name

class Brand(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='products')
    status = models.CharField(choices=STATUS, max_length=100)
    def __str__(self):
        return self.name

class Slider(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='products')
    status = models.CharField(choices=STATUS, max_length=100)
    def __str__(self):
        return self.name        

class Category(models.Model):
    title = models.CharField(max_length=200)
    logo = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    def __str__(self):
        return self.title 

class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products')
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=300,null=True,blank=True)
    return_policy = models.CharField(max_length=300,null=True,blank=True)
    view_count = models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.title             

class Customer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200) 
    address = models.CharField(max_length=200,null =True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)  
    def __str__(self):
        return self.full_name

class Cart(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL,null=True,blank=True)
    total = models.PositiveIntegerField(default=0) 
    created_at = models.DateTimeField(auto_now_add=True)  
    def __str__(self):
        return "Cart: "+str(self.id) 

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField() 
    def __str__(self):
        return "Cart: "+str(self.cart.id)+"CartProduct: "+str(self.id)   


ORDER_STATUS= (
    ("Order Received","Order Received"),
    ("Order Processing","Order Processing"),
    ("Order Completed","Order Completed"),
    ("Order Cancled","Order Cancled"),
    ("On the way","On the way")
)
METHOD = (
    ("Cash On Delivery","Cash On Delivery"),
    ("khalti","khalti"),
)

class Order(models.Model):
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True,blank=True)
    subtotal = models.PositiveIntegerField() 
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=60, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True) 
    payment_method = models.CharField(max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(default=False, null=True, blank=True)
    def __str__(self):
        return "Order: "+ str(self.id) 

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=20)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=20)
    def __str__(self):
        return self.user.username

templates/adminpages/adminbase.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>E-Site Admin Page</title>
    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Code+Pro:700,900&display=swap" rel="stylesheet">

    <!-- CSS Libraries -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="{% static 'lib/slick/slick.css' %}" rel="stylesheet">
    <link href="{% static 'lib/slick/slick-theme.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>
    <!-- Top bar Start -->
    <div class="top-bar">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6">
                    <i class="fa fa-envelope"></i>
                    Broadwayinfosis@email.com
                </div>
                <div class="col-sm-6">
                    <i class="fa fa-phone-alt"></i>
                    01-4111849
                </div>
            </div>
        </div>
    </div>
    <!-- Top bar End -->

    <!-- Nav Bar Start -->
    <div class="nav">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto">
                        <a href="{% url 'ecomapp:adminhome' %}" class="nav-item nav-link active">Home</a> |
                        <a href="{% url 'ecomapp:home' %}" target="_blank" class="nav-item nav-link active">Visit site</a> |
                        <a href="{% url 'ecomapp:adminorderlist' %}" class="nav-item nav-link active">All Orders</a> |
                    </div>
                </div>   
            </nav>
        </div>
    </div>
    <!-- Nav Bar End -->

    {% block content %}

    {% endblock %}

    <!-- Footer Start -->
    <div class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="footer-widget">
                        <h2>Get in Touch</h2>
                        <div class="contact-info">
                            <p><i class="fa fa-map-marker"></i>Pokhara-17, Chorepatan Nepal</p>
                            <p><i class="fa fa-envelope"></i>Broadwayinfosis@gmail.com</p>
                            <p><i class="fa fa-phone"></i>01-4111849</p>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="footer-widget">
                        <h2>Follow Us</h2>
                        <div class="contact-info">
                            <div class="social">
                                <a href="https://twitter.com" target="_blank"><i class="fab fa-twitter"></i></a>
                                <a href="https://facebook.com" target="_blank"><i class="fab fa-facebook-f"></i></a>
                                <a href="https://linkedin.com" target="_blank"><i class="fab fa-linkedin-in"></i></a>
                                <a href="https://instagram.com" target="_blank"><i class="fab fa-instagram"></i></a>
                                <a href="https://youtube.com" target="_blank"><i class="fab fa-youtube"></i></a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="footer-widget">
                        <h2>Company Info</h2>
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Terms & Condition</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="footer-widget">
                        <h2>Purchase Info</h2>
                        <ul>
                            <li><a href="#">Pyament Policy</a></li>
                            <li><a href="#">Shipping Policy</a></li>
                            <li><a href="#">Return Policy</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="row payment align-items-center">
                <div class="col-md-6">
                    <div class="payment-method">
                        <h2>We Accept:</h2>
                        <img src="{% static 'img/payment-method.png' %}" alt="Payment Method" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="payment-security">
                        <h2>Secured By:</h2>
                        <img src="{% static 'img/godaddy.svg' %}" alt="Payment Security" />
                        <img src="{% static 'img/norton.svg' %}" alt="Payment Security" />
                        <img src="{% static 'img/ssl.svg' %}" alt="Payment Security" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->

    <!-- Footer Bottom Start -->
    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-6 copyright">
                    <p>Copyright &copy; <a href="https://htmlcodex.com">Aakash Shah</a>. All Rights Reserved</p>
                </div>

                <div class="col-md-6 template-by">
                    <p>Template By <a href="https://htmlcodex.com">Aakash Shah</a></p>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer Bottom End -->

    <!-- Back to Top -->
    <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/slick/slick.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>  

templates/adminpages/adminhome.html
{% extends 'adminpages/adminbase.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Pending Orders</h3>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Customers</th>
                        <th>Order ID</th>
                        <th>Ordered On</th>
                        <th>Amount</th>
                    </tr>    
                </thead>
                <tbody>
                    {% for order in pendingorders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{order.ordered_by}}</td>
                        <td><a href="{% url 'ecomapp:adminorderdetail' order.id %}">#ORDER_{{order.id}}</a></td>
                        <td>{{order.created_at}}</td>
                        <td>{{order.total}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

templates/adminpages/adminlogin.html
{% extends 'adminpages/adminbase.html' %}
{% load static %}
{% block content %}

<div class="conatiner">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Admin Login Form</h3>
            <hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn">Admin Login</button>
                {% if error %}
                <li style="color: rgb(255, 0, 85);">{{error}}</li>
                {% endif %}
            </form>
        </div>
    </div>
</div>        
        

 {% endblock %}

templates/adminpages/adminorderdetail.html
{% extends 'adminpages/adminbase.html' %}
{% load static %}
{% block content %}
{% load humanize %}

<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h3>Order Details</h3>
            <hr>
            <p><span class="font-weight-bold">Order ID = </span>#Order_{{ord_obj.id}}</p>
            <p><span class="font-weight-bold">Order Status = </span>{{ord_obj.order_status}}</p>
            <p><span class="font-weight-bold">Order ON = </span>{{ord_obj.created_at}}({{ord_obj.created_at|timesince}}) ago</p>
            <p><span class="font-weight-bold">Order by = </span>{{ord_obj.ordered_by}}</p>
            <p><span class="font-weight-bold">Mobile Number = </span>{{ord_obj.mobile}}</p>
            <p><span class="font-weight-bold">Shipping Address = </span>{{ord_obj.shipping_address}}</p>
            <p><span class="font-weight-bold">Payment Information = </span>Using {{ord_obj.payment_method}} 
                ({%if ord_obj.payment_completed %}Payment Completed{% else %}Not Paid{% endif %})</p>
            <hr>
            <hr>
            <h4>Ordered Information</h4>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Item</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        {% for cp in ord_obj.cart.cartproduct_set.all %}
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'ecomapp:productdetail' cp.product.slug %}" target="_blank">{{cp.product.title}}({{cp.product.id}})</a></td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>    
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total = </th>
                        <th>Rs {{ord_obj.total|intcomma}}/-</th>
                    </tr>
                </tbody>
            </table>
            <form action="{% url 'ecomapp:adminorderstatuschange' ord_obj.id %}" method="POST">
                 {% csrf_token %}
                 <select name="status">
                     {% for i,j in allstatus %}
                     <option value="{{i}}" {% if i == ord_obj.order_status %}selected{% endif %}>{{j}}</option>
                     {% endfor %}
                 </select>   
                 <button class="btn">Change</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/adminpages/adminorderlist.html
{% extends 'adminpages/adminbase.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>All Orders</h3>
            <hr>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Customers</th>
                        <th>Order ID</th>
                        <th>Ordered On</th>
                        <th>Amount</th>
                        <th>Status</th>
                    </tr>    
                </thead>
                <tbody>
                    {% for order in allorders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{order.ordered_by}}</td>
                        <td><a href="{% url 'ecomapp:adminorderdetail' order.id %}">#ORDER_{{order.id}}</a></td>
                        <td>{{order.created_at}}</td>
                        <td>{{order.total}}</td>
                        <td>{{order.order_status}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}