ecomapp/urls.py
from django.urls import path
from .views import *

app_name = "ecomapp"
urlpatterns = [
    path("", HomeView.as_view(), name ="home"),
    path("all-products/", AllProductsView.as_view(), name ="allproducts"),
    path("products/<slug:slug>/", ProductDetailView.as_view(), name ="productdetail"),
    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name ="addtocart"),
    path("my-cart/", MyCartView.as_view(), name ="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name ="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name ="emptycart"),
    path("checkout/", CheckoutView.as_view(), name ="checkout"),
    path("register/", CustomerRegistrationView.as_view(), name ="customerregistration"),
    path("logout/", CustomerLogoutView.as_view(), name ="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name ="customerlogin"),
    path("profile/", CustomerProfileView.as_view(), name ="customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(), name ="customerorderdetail"),

    path("admin-login/", AdminLoginView.as_view(), name ="adminlogin"),
    path("admin-home/", AdminHomeView.as_view(), name ="adminhome"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(), name ="adminorderdetail"),
    path("admin-all-orders/", AdminOrderListView.as_view(), name ="adminorderlist"),
    path("admin-order-<int:pk>-change/", AdminOrderStatusChangeView.as_view(), name ="adminorderstatuschange"),

    path("search/", SearchView.as_view(), name ="search"),
    path("khalti/", KhaltiView.as_view(), name="khalti"),
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),
]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("ecomapp.urls")),
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

STATUS = (('active','Active'),('inactive','Inactive'))

class Ad(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='products')
    rank = models.IntegerField()
    status = models.CharField(choices=STATUS, max_length=100)
    def __str__(self):
        return self.name

class Brand(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='products')
    status = models.CharField(choices=STATUS, max_length=100)
    def __str__(self):
        return self.name

class Slider(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='products')
    status = models.CharField(choices=STATUS, max_length=100)
    def __str__(self):
        return self.name        

class Category(models.Model):
    title = models.CharField(max_length=200)
    logo = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    def __str__(self):
        return self.title 

class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products')
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=300,null=True,blank=True)
    return_policy = models.CharField(max_length=300,null=True,blank=True)
    view_count = models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.title             

class Customer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200) 
    address = models.CharField(max_length=200,null =True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)  
    def __str__(self):
        return self.full_name

class Cart(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL,null=True,blank=True)
    total = models.PositiveIntegerField(default=0) 
    created_at = models.DateTimeField(auto_now_add=True)  
    def __str__(self):
        return "Cart: "+str(self.id) 

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField() 
    def __str__(self):
        return "Cart: "+str(self.cart.id)+"CartProduct: "+str(self.id)   


ORDER_STATUS= (
    ("Order Received","Order Received"),
    ("Order Processing","Order Processing"),
    ("Order Completed","Order Completed"),
    ("Order Cancled","Order Cancled"),
    ("On the way","On the way")
)
METHOD = (
    ("Cash On Delivery","Cash On Delivery"),
    ("khalti","khalti"),
)

class Order(models.Model):
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True,blank=True)
    subtotal = models.PositiveIntegerField() 
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=60, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True) 
    payment_method = models.CharField(max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(default=False, null=True, blank=True)
    def __str__(self):
        return "Order: "+ str(self.id) 

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=20)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=20)
    def __str__(self):
        return self.user.username

templates/addtocart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <h3>Product added to cart successfully. </h3>
</div>

{% endblock %}

templates/allproducts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    {% for cat in allcategories %}
    <hr>
    <h2>{{cat.title}}</h2>
    <hr>
    <div class="row">
        {% for p in cat.product_set.all %}
        <div class="col-md-4">
            <div class="m-4">
                <h3><a href="{% url 'ecomapp:productdetail' p.slug %}">{{p.title}}</a></h3>
                <img src="{{p.image.url}}" alt="" width="250" height=250; object-fit:cover >
                <p class="mt-3">Price: <strike>Rs. {{p.marked_price}}</strike> Rs. {{p.selling_price}}</p>
                <a href="{% url 'ecomapp:addtocart' p.id %}" class="btn btn-primary">Add To Cart</a>
            </div>
        </div>
        {% endfor %}  
    </div>
    {% endfor %}
</div>


{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>E-Site</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="eCommerce HTML Template Free Download" name="keywords">
        <meta content="eCommerce HTML Template Free Download" name="description">

        <!-- Favicon -->
        <link href="{% static 'img/favicon.ico' %}" rel="icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Code+Pro:700,900&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'lib/slick/slick-theme.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>

    <body>
        <!-- Top bar Start -->
        <div class="top-bar">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <i class="fa fa-envelope"></i>
                        Broadwayinfosis@email.com
                    </div>
                    <div class="col-sm-6">
                        <i class="fa fa-phone-alt"></i>
                        01-4111849
                    </div>
                </div>
            </div>
        </div>
        <!-- Top bar End -->

        <!-- Nav Bar Start -->
        <div class="nav">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto">
                            <a href="{% url 'ecomapp:home' %}" class="nav-item nav-link active">Home</a> |
                            <a href="{% url 'ecomapp:mycart' %}" class="nav-item nav-link active">Cart</a> |
                            <a href="{% url 'ecomapp:allproducts' %}" class="nav-item nav-link active">Categories</a> |
                            {% if request.user.customer %}
                            Welcome {{request.user.username}} |
                            <a href="{% url 'ecomapp:customerprofile' %}" class="nav-item nav-link active">My Profile</a> |
                            <a href="{% url 'ecomapp:customerlogout' %}" class="nav-item nav-link active">Logout</a> |
                            {% else %}
                            <a href="{% url 'ecomapp:customerregistration' %}" class="nav-item nav-link active">Registeration</a> |
                            <a href="{% url 'ecomapp:customerlogin' %}" class="nav-item nav-link active">Login</a> |
                            {% endif %}
                        </div>
                    </div>   
                </nav>
            </div>
        </div>
        <!-- Nav Bar End -->

        <!-- Bottom Bar Start -->
        <div class="bottom-bar">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-md-3">
                        <div class="logo">
                            <a href="/">
                                <img src="{% static 'img/logo.png' %}">
                            </a>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <form method="GET" action="{% url 'ecomapp:search' %}">
                        <div class="search">
                            <input name="keyword" type="text" placeholder="Search  ...." required>
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </div>
                        </form>
                    </div>
                    <div class="col-md-3">
                        <div class="user">
                            <a href="wishlist.html" class="btn btn-wishlist">
                                <i class="fa fa-heart"></i>
                                <span class="badge badge-info"></span>
                            </a>
                            <a href="" class="btn btn-cart">
                                <i class="fa fa-shopping-cart"></i>
                                <span class="badge badge-info"></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Bottom Bar End -->
  {% block content %}

  {% endblock %} 

    <!-- Review Start -->
    <div class="review">
        <div class="container-fluid">
            <div class="row align-items-center review-slider normal-slider">
                <div class="col-md-6">
                    <div class="review-slider-item">
                        <div class="review-img">
                            <img src="{% static 'img/man-2.jpg' %}" alt="Image">
                        </div>
                        <div class="review-text">
                            <h2>Aakash Shah</h2>
                            <h3>Data Sceintist</h3>
                            <div class="ratting">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </div>
                            <p>
                                This website is userfriendly and easy to use and provides best quality with cheap prices.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="review-slider-item">
                        <div class="review-img">
                            <img src="{% static 'img/man-1.jpg' %}" alt="Image">
                        </div>
                        <div class="review-text">
                            <h2>Aashish Shah</h2>
                            <h3>Footbaler</h3>
                            <div class="ratting">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </div>
                            <p>
                                I need good football shoes .due to insufficent time to visit stores ,browse some online shoping website
                                and i got this with best and good satisfaction
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="review-slider-item">
                        <div class="review-img">
                            <img src="{% static 'img/man.jpg' %}" alt="Image">
                        </div>
                        <div class="review-text">
                            <h2>Aadip Shah</h2>
                            <h3>Army</h3>
                            <div class="ratting">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </div>
                            <p>
                                This site is very good for those who lack confidence and trust to online sites. This sites
                                is very reliable and trustworthy..
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Review End --> 
            <!-- Footer Start -->
        <div class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Get in Touch</h2>
                            <div class="contact-info">
                                <p><i class="fa fa-map-marker"></i>Pokhara-17, Chorepatan Nepal</p>
                                <p><i class="fa fa-envelope"></i>Broadwayinfosis@gmail.com</p>
                                <p><i class="fa fa-phone"></i>01-4111849</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Follow Us</h2>
                            <div class="contact-info">
                                <div class="social">
                                    <a href="https://twitter.com" target="_blank"><i class="fab fa-twitter"></i></a>
                                    <a href="https://facebook.com" target="_blank"><i class="fab fa-facebook-f"></i></a>
                                    <a href="https://linkedin.com" target="_blank"><i class="fab fa-linkedin-in"></i></a>
                                    <a href="https://instagram.com" target="_blank"><i class="fab fa-instagram"></i></a>
                                    <a href="https://youtube.com" target="_blank"><i class="fab fa-youtube"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Company Info</h2>
                            <ul>
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                                <li><a href="#">Terms & Condition</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Purchase Info</h2>
                            <ul>
                                <li><a href="#">Pyament Policy</a></li>
                                <li><a href="#">Shipping Policy</a></li>
                                <li><a href="#">Return Policy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="row payment align-items-center">
                    <div class="col-md-6">
                        <div class="payment-method">
                            <h2>We Accept:</h2>
                            <img src="{% static 'img/payment-method.png' %}" alt="Payment Method" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="payment-security">
                            <h2>Secured By:</h2>
                            <img src="{% static 'img/godaddy.svg' %}" alt="Payment Security" />
                            <img src="{% static 'img/norton.svg' %}" alt="Payment Security" />
                            <img src="{% static 'img/ssl.svg' %}" alt="Payment Security" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->

        <!-- Footer Bottom Start -->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 copyright">
                        <p>Copyright &copy; <a href="https://htmlcodex.com">Aakash Shah</a>. All Rights Reserved</p>
                    </div>

                    <div class="col-md-6 template-by">
                        <p>Template By <a href="https://htmlcodex.com">Aakash Shah</a></p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Bottom End -->

        <!-- Back to Top -->
        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'lib/slick/slick.min.js' %}"></script>

        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Items in the cart</h2>
            <a href="{% url 'ecomapp:mycart' %}" class="btn">Update Cart</a>
            <a href="/" class="btn">Shopping Again</a>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <h2>Checkout Form</h2>
            <form method="POST" action="">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn">Place Order</button>
            </form>
        </div>            
    </div>
</div>    
<hr>        

{% endblock %}

templates/customerlogin.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'ecomapp:mycart' %}">Cart</a></li>
            <li class="breadcrumb-item active"><a href="{% url 'ecomapp:customerregistration' %}>Register</a></li>
        </ul>
    </div>
</div>
<!-- Breadcrumb End -->

<div class="conatiner">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Customer Login Form</h3>
            <hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn">Customer Login</button>
                {% if error %}
                <li style="color: aqua;">{{error}}</li>
                {% endif %}
            </form>
            <hr>
            <p>Don't have account ? <a href="{% url 'ecomapp:customerregistration' %}
                {% if request.GET.next %}?next={{request.GET.next}}{% endif %}" class="btn">Register Now</a></p>
        </div>
    </div>
</div>        
        

 {% endblock %}

templates/customerorderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load humanize %}

<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h3>Order Details</h3>
            <hr>
            <p><span class="font-weight-bold">Order ID = </span>#Order_{{ord_obj.id}}</p>
            <p><span class="font-weight-bold">Order Status = </span>{{ord_obj.order_status}}</p>
            <p><span class="font-weight-bold">Order ON = </span>{{ord_obj.created_at}}({{ord_obj.created_at|timesince}}) ago</p>
            <p><span class="font-weight-bold">Order by = </span>By {{ord_obj.order_by}}</p>
            <p><span class="font-weight-bold">Mobile Number = </span>{{ord_obj.mobile}}</p>
            <p><span class="font-weight-bold">Shipping Address = </span>{{ord_obj.shipping_address}}</p>
            <hr>
            <hr>
            <h4>Ordered Information</h4>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Item</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        {% for cp in ord_obj.cart.cartproduct_set.all %}
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'ecomapp:productdetail' cp.product.slug %}" target="_blank">{{cp.product.title}}({{cp.product.id}})</a></td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>    
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total = </th>
                        <th>Rs {{ord_obj.total|intcomma}}/-</th>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock %}

templates/customerregistration.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'ecomapp:mycart' %}">Cart</a></li>
            <li class="breadcrumb-item active">Register</li>
        </ul>
    </div>
</div>
<!-- Breadcrumb End -->

<div class="conatiner">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Customer Registeration Form</h3>
            <hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn">Customer Registeration Form</button>
            </form>
            <hr>
            <p>Already have account <a href="{% url 'ecomapp:customerlogin' %}" class="btn">Login Now</a></p>
        </div>
    </div>
</div>        
        

 {% endblock %}

templates/mycart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

   <!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/">Products</a></li>
            <li class="breadcrumb-item active">Cart</li>
        </ul>
    </div>
</div>
<!-- Breadcrumb End -->

<!--cart start-->
<div class="cart-page">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-8">
                <div class="cart-page-inner">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead class="thead-dark">
                                <tr>
                                    <th>SN</th>
                                    <th>Product</th>
                                    <th>Rate</th>
                                    <th>Quantity</th>
                                    <th>Subtotal</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for cp in cart.cartproduct_set.all %}
                                <tr>
                                    <td>{{forloop.counter}}</td>
                                    <td>{{cp.product.title}}</td>
                                    <td>{{cp.rate}}</td>
                                    <td>{{cp.quantity}}</td>
                                    <td>{{cp.subtotal}}</td>
                                    <td>
                                        <a href="{% url 'ecomapp:managecart' cp.id %}?action=inc" class="btn">+</a>
                                        <a href="{% url 'ecomapp:managecart' cp.id %}?action=dcr" class="btn">-</a>
                                        <a href="{% url 'ecomapp:managecart' cp.id %}?action=rmv" class="btn">x</a>
                                    </td>
                                </tr>
                                {% endfor %}
                                <tr>
                                    <th colspan="4" class="text-right">Total</th>
                                    <th> Rs. {{cart.total}}</th>
                                </tr>    
                                {% if cart.cartproduct_set.all %}
                                <tr>
                                    <th><a class="btn" href="{% url 'ecomapp:emptycart' %}">Empty Cart</a></th>
                                </tr>
                                {% endif %}
                                {% if cart.cartproduct_set.all %}
                                <tr>
                                    <th><a class="btn" href="{% url 'ecomapp:checkout' %}">Checkout</a></th>
                                </tr>
                                {% endif %}
                                <tr>
                                    <th><a href="/" class="btn">Shopping Again</a></th>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>           
<!--cart end-->


{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'ecomapp:mycart' %}">Cart</a></li>
            <li class="breadcrumb-item active"><a href="{% url 'ecomapp:customerregistration' %}">Register</a></li>
        </ul>
    </div>
</div>
<!-- Breadcrumb end -->

<div class="container">
    <div class="row">
        <div class="col-md-12">
          <h3>Search Results of <span class="badge text-info">"{{request.GET.keyword}}"</span></h3>
          <hr> 
          {% for result in results %}
            <div class="row">
                <div class="col-md-4">
                    <img src="{{result.image.url}}" class="img-fluid" alt="" height="600" width="350">
                </div>
                <div class="col-md-8">
                    <h4><a href="{% url 'ecomapp:productdetail' result.slug %}">{{result.title}}</a></h4>
                    <p>{{result.description|truncatewords:50}}</p>
<!--if we do truncatechars:40 then descriptions will be shown upto 40 words -->  
                    <p>Return Policy = {{result.return_policy}}</p>
                    <p>Warranty = {{result.warranty}}</p>
                    <a href="{% url 'ecomapp:addtocart' result.id %}" class="btn btn-primary">Add To Cart</a>
                </div>
            </div>
          {% endfor %} 
        </div>
    </div>
</div>
<hr>
<hr>

{%endblock%}